server:
  port: 8082

spring:
  application:
    name: auth-service




eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka

logging:
  level:
    com.leyou: debug

ly:
  oss:
    accessKeyId: LTAI4G3HEXqMMhDp6Qan3A5Y
    accessKeySecret: j6B0IQolP7Xx74pQ3he4yl0sLSrD1x
    host: http://xiaochao981.oss-cn-shanghai.aliyuncs.com # 访问oss的bucket的域名
    endpoint: oss-cn-shanghai.aliyuncs.com # 你选择的oss服务器的地址
    dir: "heima" # 保存到bucket的某个子目录
    expireTime: 1200000 # 过期时间，单位是ms
    maxFileSize: 5242880 #文件大小限制，这里是5M
